name: jormungandr-server CD

on:
  push:
    branches: [main, release/**]
jobs:
  deploy:
    runs-on: ubuntu-latest
    #needs: test


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.5.0

      - name: Deploy production
        uses: appleboy/ssh-action@v0.1.5

        with:
          script_stop: true
          key: ${{ secrets.KEY }}
          host: ${{ secrets.HOST }}
          username: centos
          script: |
            whoami
            cd /home/centos/server/jormungandr
            git checkout main
            git fetch --all
            git reset --hard origin/main
            git pull origin main
            export NODE_ENV=development && yarn
            yarn run build
            export NODE_ENV=production && pm2 reload 5

      - name: Notify on SUCCESS
        if: ${{ success() }}
        uses: ./.github/actions/notification
        with:
          status: SUCCESS

      - name: Notify on FAIL
        if: ${{ failure() }}
        uses: ./.github/actions/notification


